version: "3"

services:
    php:
        image: alexdwt/example-php:latest
        build:
            context: '.'
            dockerfile: 'php/Dockerfile'
        volumes:
            - /home/alex/Projects/docker-example/app:/app
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        environment:
            - DB_HOST
            - DB_PORT
            - DB_NAME
            - DB_USER
            - DB_PASS
        networks:
            - webnet

    front:
        image: alexdwt/example-front:latest
        build: 'nginx'
        ports:
              - 80:80
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        networks:
              - webnet

    database:
        image: postgres:9.6
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASS}
            - PGPASSWORD=${DB_PASS}
        networks:
            - webnet

networks:
  webnet:

volumes:
   pgdata: